### ISSUE TITLE
css-minimizer-webpack-plugin asking for postcss peer dependency when I'm not using postcss

### ISSUE THREAD

**Issue by testacode** [webpack-contrib/css-minimizer-webpack-plugin#106]
- Operating System: OSX 10.15.7 
- Node Version: 12.16.3
- NPM Version: 6.14.11
- webpack Version: 5.44.0
- css-minimizer-webpack-plugin Version: 3.0.2

### Expected Behavior
 It should build the library for production environment

### Actual Behavior
It's breaking the build due to the lack of postcss dependency which I don't need as I don't use any postcss:
```
ERROR in federated/components/index.acf1294b0dba07ff0d0c.css
federated/components/index.acf1294b0dba07ff0d0c.css from Css Minimizer
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

### Code

https://gist.github.com/testacode/f1452bfb2c906270b9325ef34be6ca8e => webpack.base
https://gist.github.com/testacode/8efb09eba940e7ca6ea6738c2b86c15f => webpack.prod

### How Do We Reproduce?
just build the library for prod env.

**Comment by alexander-akait** [comment]
Run `npm ls postcss`

**Comment by testacode** [comment]
> Run `npm ls postcss`
This is without having postcss installed at all in any of my repos
![image](https://user-images.githubusercontent.com/1852080/125816775-5247dc8b-1747-4a09-b46b-f5fb4eeb6139.png)

I first installed it to the builder (I have it in a separate repository so I can build several other repos) didn't work
![image](https://user-images.githubusercontent.com/1852080/125816971-46329f38-b0af-45d4-9576-5480f47ba08b.png)

**Comment by testacode** [comment]
Also there's no requirement stated in the plugin's repo nor in the webpack config about this peer dependency.

**Comment by alexander-akait** [comment]
No problems with plugin here, we don't use magic here, postcss in our deps, we can't fix hoist dependencies here

**Comment by testacode** [comment]
Is there any alternative to minimize css that don't use postcss?

**Comment by testacode** [comment]
the weird thing is that you don't require postcss as a peer... https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/package.json

**Comment by alexander-akait** [comment]
We use cssnano and it **require** postcss, so we have it in deps https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/package.json#L51

**Comment by alexander-akait** [comment]
Don't know what we should fix here

**Comment by testacode** [comment]
We can close this, I still don't understand why it's an unmet peer dependency when you guys are clearly adding it as a dependency... only god and js interpreter knows...

**Comment by alexander-akait** [comment]
Can you try `npm` v7?

**Comment by testacode** [comment]
> Can you try `npm` v7? Maybe bug in npm (I think)

Sorry but npm 7 isn't working properly on our env.

**Comment by fregante** [comment]
This should probably be reopened. I did a clean lockless install (npm 6 for now) and I have the latest version. I'm seeing the same issue.

**Comment by alexander-akait** [comment]
How we can fix it here?

**Comment by fregante** [comment]
Since `css-minimizer-webpack-plugin` runs postcss internally, as opposed to sharing code with other parts of the "application", it should be declared as direct dependency, not a peer dependency.

`peerDependencies` would make sense if `css-minimizer-webpack-plugin` was a PostCSS plugin and _I_ was running PostCSS, but I'm not, I'm installing a webpack plugin.

**Comment by fregante** [comment]
Uh, it looks like `postcss` _is_ a direct dependency of this plugin, I'm not entirely sure what the problem is.

**Comment by alexander-akait** [comment]
Yes, what is npm version?

**Comment by fregante** [comment]
```
node v14.17.0 (with npm 6.14.13)
```

**Comment by alexander-akait** [comment]
can you try `npm v7`?

**Comment by fregante** [comment]
npm 7 does work but as suggested above that's not a solution for many (especially because it requires a new lockfile)

**Comment by alexander-akait** [comment]
@fregante what is problem with npm v7? Works fine for me, npm v6 has bugs, we can't fix it here
