### ISSUE TITLE
Jest worker doesn't let me see actual error, shows UnhandledPromiseRejectionWarning instead

### ISSUE THREAD

**Issue by mattiagiuffrida-st** [webpack-contrib/css-minimizer-webpack-plugin#113]
- Operating System: macOS Big Sur
- Node Version: v14.15.4
- NPM Version: 6.14.10 (yarn 1.22.10)
- webpack Version: 5.38.1 (webpacker 6.0.0-beta.7)
- css-minimizer-webpack-plugin Version:  3.0.2

### Expected Behavior

When an error happens while running CssMinimizerPlugin, I should be able to see what's wrong so I can fix it.

### Actual Behavior

Jest Worker swallows the error and doesn't show me a meaningful backtrace, I have no idea how to fix it.
This is all I see in the compilation output...

```
92% sealing asset processing CssMinimizerPlugin
UnhandledPromiseRejectionWarning: DataCloneError: function destructLexErrorInfo() {
          // remove cyclic references added to error info:
          // info....<omitted>... } could not be cloned.
    at reportError (/Users/mattiagiuffrida/Development/sensortower/overseer/node_modules/jest-worker/build/workers/threadChild.js:100:32)
    at reportClientError (/Users/mattiagiuffrida/Development/sensortower/overseer/node_modules/jest-worker/build/workers/threadChild.js:84:10)
```

### Code

```js
const { webpackConfig, merge } = require('@rails/webpacker');

process.env.NODE_ENV = process.env.NODE_ENV || 'production';

const prodConfig = {
  mode: 'production',
  devtool: false,
  optimization: {
    chunkIds: 'size',
    splitChunks: {
      cacheGroups: {
        default: false,
      },
    },
    runtimeChunk: false,
  }
};

module.exports = merge(webpackConfig, prodConfig);
```

### How Do We Reproduce?

Hard to say since I don't know what's wrong 😄 !

**Comment by mattiagiuffrida-st** [comment]
For future readers, as an interim "solution" I manually changed the `reportError` function in `node_modules/jest-worker/build/workers/threadChild.js` adding a few `console.log` statements:

```javascript
function reportError(error, type) {
  if (_worker_threads().isMainThread) {
    throw new Error('Child can only be used on a forked process');
  }

  if (error == null) {
    error = new Error('"null" or "undefined" thrown');
  }

  // Add console.log to see the actual error
  console.log(error.constructor?.name);
  console.log(error.message);
  console.log(error.stack.join("\n"));

  _worker_threads().parentPort.postMessage([
    type,
    error.constructor && error.constructor.name,
    error.message,
    error.stack,
    typeof error === 'object' ? {...error} : error
  ]);
}
```

This allowed me to find a fix the underlying issue (it was an incorrect variable interpolation inside `calc()`), but I should not be making changes to packages inside my `node_modules` folder to debug an issue, so I hope there was a way to see the error without doing that

**Comment by alexander-akait** [comment]
Please report this to `jest-worker`, as you can see we can't fix it on our side

**Comment by mattiagiuffrida-st** [comment]
Mmmmh I've never used `jest-worker`, but are you sure there's isn't a better way to raise exceptions so that they're correctly caught and reported? I'd be surprised if this was uniquely a `jest-worker` issue affecting all exceptions raised inside a worker to be honest...

**Comment by alexander-akait** [comment]
We use `jest-worker` in our deps, maybe you can provide small example to reproduce the problem, I think `jest-worker` should better handle errors

**Comment by mattiagiuffrida-st** [comment]
Here you go: https://github.com/mattiagiuffrida-st/css-minimizer-webpack-plugin-error
Just clone the repo and run the following:

```bash
yarn
yarn run production
```

You'll see the `UnhandledPromiseRejectionWarning` error I was talking about.
The ACTUAL error is [here](https://github.com/mattiagiuffrida-st/css-minimizer-webpack-plugin-error/blob/master/src/scss/demo.scss#L19), but it's hard to say looking at the error message

**Comment by mattiagiuffrida-st** [comment]
Thanks for looking into it @alexander-akait, I'll do that and point to your comment as well as I'm sure it will help the Jest team 👍

**Comment by phil-lgr** [comment]
This might help more people until the jest-worker issue is resolved.

In `node_modules/jest-worker/build/workers/threadChild.js`, replace the `reportError` with this (modified version of the code above, since stack.join does not always exist):

```js
function reportError(error, type) {
  if (_worker_threads().isMainThread) {
    throw new Error('Child can only be used on a forked process');
  }

  if (error == null) {
    error = new Error('"null" or "undefined" thrown');
  }

  // Add console.log to see the actual error
  delete error.hash
  if(error.constructor){
    console.log(error.constructor.name);
  }
  if(error.message){
    console.log(error.message);
  }
  if(error.stack && error.stack.length){
    console.log(error.stack);
  }

  _worker_threads().parentPort.postMessage([
    type,
    error.constructor && error.constructor.name,
    error.message,
    error.stack,
    typeof error === 'object' ? {...error} : error
  ]);
}
```

I was able to see where the error was coming from.
