### ISSUE TITLE
I do not understand how it works with TerserPlugin

### ISSUE THREAD

**Issue by Hideman85** [webpack-contrib/css-minimizer-webpack-plugin#116]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

I do not understand how it works with TerserPlugin and I'm not the first one https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/46

```js
minimize: isEnvProduction,
minimizer: [
  // This is only used in production mode
  new TerserPlugin({
    parallel: true,
    terserOptions: {
      parse: {
        ecma: 8
      },
      // ...
    }
  }),
  new CssMinimizerPlugin({
    minimizerOptions: {
      processorOptions: {
        parser: safePostCssParser,
        map: false
      },
      preset: ['default', {
        discardComments: { removeAll: true },
        minifyFontValues: { removeQuotes: false }
      }]
    }
  })
  /*
    Creating an optimized production build...
    Error parsing bundle asset "/home/user/project/build/js/app.js": no such file
    Error parsing bundle asset "/home/user/project/build/js/loading.js": no such file

    No bundles were parsed. Analyzer will show only original module sizes from stats file.

    Webpack Bundle Analyzer saved report to /home/user/project/sizeReport.html
    Failed to compile.

    css/loading.css from Css Minimizer
    ReferenceError: Input is not defined
  */

  // ...new CssMinimizerPlugin(...) // TypeError: CssMinimizerPlugin is not a function or its return value is not iterable
],
```

I tried also this
```js
minimize: isEnvProduction,
minimizer: [
  new TerserPlugin({
    // ...
    ...new CssMinimizerPlugin(...)
    /*
      ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
       - options has an unknown property 'options'.
     */
    
    ...new CssMinimizerPlugin(...).options
    /*
      ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
       - options has an unknown property 'minimizerOptions'.
     */
  })
]
```

**Comment by alexander-akait** [comment]
```js
minimizer: [
  '...',
  new CssMinimizerPlugin({
    minimizerOptions: {
      processorOptions: {
        parser: safePostCssParser,
        map: false
      },
      preset: ['default', {
        discardComments: { removeAll: true },
        minifyFontValues: { removeQuotes: false }
      }]
    }
  })
```

**Comment by alexander-akait** [comment]
It is just array with plugins, but using `'...'` apply default `minimizer`, i.e. `terser-webpack-plugin`

**Comment by Hideman85** [comment]
Sorry, I still do not understand it could be obvious to you, but for me, it is not.

I currently have TerserPlugin with some custom options, followed by OptimizeCSSAssetsPlugin with some options too. I'm trying now to use your plugin as the replacement of OptimizeCSSAssetsPlugin, but I need to keep my config of both plugins.

In my previous webpack config was working with `minimizer: [new TerserPlugin(...), new OptimizeCSSAssetsPlugin(...)]`

When I simply replace OptimizeCSSAssetsPlugin by CssMinimizerPlugin like `minimizer: [new TerserPlugin(...), new CssMinimizerPlugin(...)]` it causing me the first issue
```
css/loading.css from Css Minimizer
ReferenceError: Input is not defined
```

.

So I do not understand. What is the meaning of the string `'...'` in the array? Is it a special webpack marker? Or is it just mean any plugin before? So please add explicitly in the readme.md for the webpack users like me that are not deeply familiar with the webpack API.

.

- In case of `'...'` is a special marker saying "default minimizer", my question is how does it select the minimizer? And how it gets the config?
- If so I would include in the readme, 
```js
minimizer: [
  '...', // This is a webpack marker for using the default minimizer. To configure it please a look at [this]()
  new CssMinimizerPlugin({
    // ...
  })
]
```
`'...'` 

.

- In case it means any other minimizer I do not explain why my config fails to compile :thinking:, does it have a relationship with the css-loader 5x or 6x?
- I would update the readme like this
```js
minimizer: [
  // ...
  // You can use any mimizer first (like TerserPlugin), please ensure CssMinimizerPlugin is the last minimizer in the array
  new CssMinimizerPlugin({
    // ...
  })
]
```

I could be dumb but if that would be the case I won’t touch any webpack config :smile:

**Comment by alexander-akait** [comment]
Please provide example how we can reproduce it
