### ISSUE TITLE
minimizerOptions.processorOptions.map not working

### ISSUE THREAD

**Issue by nolimitdev** [webpack-contrib/css-minimizer-webpack-plugin#138]
### Bug report

processorOptions with `{ map : { inline : ..., annotation : ... } }` does not work. 

### Actual Behavior

Changing `inline` true/false and `annotation` true/false does nothing - the same result.

### Expected Behavior

When e.g. `inline` = false source map should not be created. Also when `inline` = true and `annotation` = false annotation in CSS file e.g. `/*# sourceMappingURL=file.css.map*/` should be omitted.

### How Do We Reproduce?

```
optimization : {
    minimizer : [
        new CssMinimizerWebpackPlugin({
            minimizerOptions : {
                preset : [ 'default', { discardComments : { removeAll : true } } ],
                processorOptions : { map : { inline : true, annotation : false } },
            },
        }),
    ],
},
```
When comparing to prev. plugin https://www.npmjs.com/package/optimize-css-assets-webpack-plugin for webpack v4 code below works well...
```
optimization : {
    minimizer : [
        new OptimizeCssAssetsPlugin({
            cssProcessorPluginOptions : { preset : [ 'default', { discardComments : { removeAll : true } } ] },
            cssProcessorOptions : { map : { inline : false, annotation : true } },
        }),
    ],
},
```
Im not sure if this is problem just with **minimizerOptions.processorOptions.map** or glbaly with **minimizerOptions.processorOptions**

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
Console is totally clean, no warns no errors just `webpack compiled successfully in N ms`

**Comment by alexander-akait** [comment]
You should not try to set source maps for minimizer, it will not work, source map generation is internal

**Comment by alexander-akait** [comment]
You can set it using `devtool` global option

**Comment by nolimitdev** [comment]
Of course I have source map set using `devtool : 'source-map'` but this issue is about configuring it https://postcss.org/api/#sourcemapoptions Configuring via https://www.npmjs.com/package/optimize-css-assets-webpack-plugin was working but does not work via https://www.npmjs.com/package/css-minimizer-webpack-plugin

**Comment by alexander-akait** [comment]
You should not do it, because you will have broken source maps

**Comment by alexander-akait** [comment]
There are a lot of variants of `devtool`

**Comment by nolimitdev** [comment]
Alternative is https://github.com/mistakster/postcss-pipeline-webpack-plugin with `map` option

**Comment by alexander-akait** [comment]
Again, you will have broken source map if you use other options for source maps
