### ISSUE TITLE
Calculations lose the required parentheses

### ISSUE THREAD

**Issue by krutoo** [webpack-contrib/css-minimizer-webpack-plugin#139]
### Actual Behavior

In my project i have `index.css`:
```css
html {
  --dot-size: 6;
}

body {
  transform: scale(calc(1 / (10 / var(--dot-size))));
}
```

and index.js

```js
import './index.css';

console.log('Hello, world!');
```

And webpack config:
```js
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'index.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [new MiniCssExtractPlugin()],
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [
      '...',
      new CssMinimizerPlugin(),
    ],
  },
};
```

After run webpack, in dist folder i have css file with content:
```css
/* ... */
body{transform: scale(calc(1/10/var(--dot-size)))}
```

**Here the `calc` function has lost the necessary parentheses around the second division:**

```
1 / (10 / 6) >>> 1 / 10 / 6
```

Looks like it is not a cssnano issue, here is a demo in playground with default preset:
https://cssnano.co/playground#eyJpbnB1dCI6ImJvZHkge1xuICAgIC0tZG90LXNpemU6IDY7XG4gICAgdHJhbnNmb3JtOiB0cmFuc2xhdGUzZCgtNTAlLC01MCUsMCkgc2NhbGUoY2FsYygxLygxMC92YXIoLS1kb3Qtc2l6ZSkpKSk7XG59IiwiY29uZmlnIjoie1xuICBcInByZXNldFwiIDogXCJkZWZhdWx0XCJcbn1cbiJ9

### Expected Behavior

Required parens should not be omitted.

### How Do We Reproduce?

For reproduce you can use code from previous sections.

Repo with example also here:
https://github.com/krutoo/css-minimizer-webpack-plugin-tests

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 37.06 MB / 4.00 GB
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  Packages:
    css-loader: ^6.5.1 => 6.5.1
    css-minimizer-webpack-plugin: ^3.1.4 => 3.1.4
    webpack: ^5.64.1 => 5.64.1
    webpack-cli: ^4.9.1 => 4.9.1
```

**Comment by alexander-akait** [comment]
Please open an issue in cssnano, we can't fix it here

**Comment by krutoo** [comment]
@alexander-akait But this problem is not reproducible on cssnano playground page

I was able to reproduce it only with css-minimizer-webpack-plugin

**Comment by alexander-akait** [comment]
Because playground uses `lite` preset, we don't modify your code, you can check it in our source code
