### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by luxalpa** [webpack-contrib/css-minimizer-webpack-plugin#141]
### Feature Proposal

This package should come with official typescript support as Webpack 5 has official typescript support. Considering this is in webpack-contrib and listed (and used) on the official webpack documentation, it should have full support for the latest webpack-version if you're using webpack.config.ts.

Although there is a `@types/` package for this, it's not being kept up-to-date so it breaks every few webpack versions (like it is currently broken for a few months). This effectively prevents typescript users of this plugin from updating webpack.

### Feature Use Case

Using in `webpack.config.ts` with latest webpack version instead of having to wait multiple months for the DT package to get updated.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: Linux 5.11 elementary OS 6 Odin
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 28.42 GB / 46.99 GB
  Binaries:
    Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v17.1.0/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v17.1.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0
  Packages:
    babel-loader: ^8.2.3 => 8.2.3 
    css-loader: ^6.5.1 => 6.5.1 
    css-minimizer-webpack-plugin: ^3.1.4 => 3.1.4 
    eslint-import-resolver-webpack: ^0.13.2 => 0.13.2 
    fork-ts-checker-webpack-plugin: ^6.4.2 => 6.4.2 
    html-inline-script-webpack-plugin: ^2.0.3 => 2.0.3 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    postcss-loader: ^6.2.0 => 6.2.0 
    style-loader: 3.3.1 => 3.3.1 
    terser-webpack-plugin: ^5.2.5 => 5.2.5 
    webpack: 5.64.2 => 5.64.2 
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-dev-server: ^4.5.0 => 4.5.0 
    webpack-manifest-plugin: 4.0.2 => 4.0.2
```

See also: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49354#issuecomment-917057375

**Comment by alexander-akait** [comment]
Here we go https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/142

**Comment by alexander-akait** [comment]
Done https://github.com/webpack-contrib/css-minimizer-webpack-plugin/releases/tag/v3.2.0
