### ISSUE TITLE
Feature request - parcel-css as custom minifier 

### ISSUE THREAD

**Issue by ankurk91** [webpack-contrib/css-minimizer-webpack-plugin#153]
### Feature Proposal
Allow [parcel-css](https://github.com/parcel-bundler/parcel-css) as custom minifier 

### Feature Use Case
We already support esbuild, so why not parcel-css

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/154, note:

- prefixes are broken and do not work
- minification is broken for special IE10/11 properties (i.e. `*prop: value`)
- collapsing properties are broken in some cases
- escaped things are broken
