### ISSUE TITLE
Adjust the config of minify

### ISSUE THREAD

**Issue by fireairforce** [webpack-contrib/css-minimizer-webpack-plugin#169]
### Modification Proposal

I want to know if change the minify way from function to a string ? 

### Expected Behavior / Situation

just write as:
```ts
minify: '@parcel/css'
```

### Actual Behavior / Situation

```ts
minify: CssMinimizerPlugin.parcelCssMinify,
```

I think it's more convenient.

**Comment by alexander-akait** [comment]
Sorry, it will require to have map of packages and functions to minify, also you can wrap function and add addional logic and even more, it is very flexibility, so no make sense to have it, sorry

**Comment by fireairforce** [comment]
ok, thanks for your response.
