### ISSUE TITLE
Feature: Add Lightning CSS (renamed @parcel/css)

### ISSUE THREAD

**Issue by LekoArts** [webpack-contrib/css-minimizer-webpack-plugin#191]
### Feature Proposal

Devon released Lightning CSS: https://twitter.com/devongovett/status/1567898042787049473
It's the same as `@parcel/css` but now with a different name.

https://lightningcss.dev/

So it'll be a matter of changing dependencies and names to support this new, old package.

I'm happy to do the work if y'all can give me directions on how you typically handle such renames. I'd imagine just removing the `parcelCssMinify` option is not ideal as it would be a breaking change. So maybe gracefully handle that option for now and fallback to the new `lightningCssMinify` option then? So the options passed to `parcelCssMinify` would be just passed through to `lightningCssMinify`.

Thanks for your work and the plugins!

**Comment by vgurkov** [comment]
I hope we get this soon. Currently `@parcel/css` only re-exports `lightningcss`. So the `parcelCssMinify` should be able to use the new package under the hood without any difference

**Comment by LekoArts** [comment]
Ah, I didn't know that, thanks for the comment! That should make things even easier 👍

**Comment by alexander-akait** [comment]
Done https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/192 + docs updated (old solution will work too, but I recommend to migrate on the new function, the old was removed in the next major release)

**Comment by LekoArts** [comment]
Thanks for the quick turnaround, appreciate it
