### ISSUE TITLE
4.0.0=>4.2.1  got  error:   enableWorkerThreads: this._options.enableWorkerThreads ?? false

### ISSUE THREAD

**Issue by townechow** [webpack-contrib/css-minimizer-webpack-plugin#201]
### Bug report
after updated: 4.0.0=>4.2.1  got error:   enableWorkerThreads: this._options.enableWorkerThreads ?? false

### Actual Behavior

 "css-minimizer-webpack-plugin": "4.2.1",
 "webpack": "5.74.0",
  error: 
 
![1665566272729_73A5F283-89A3-4359-AC9A-C36BEB84A29F](https://user-images.githubusercontent.com/35532710/195305547-97be7727-4f35-4654-a3bf-846ae770a040.png)

"css-minimizer-webpack-plugin": "4.0.0" is ok

**Comment by alexander-akait** [comment]
You need to update Node.js version to use, our minimum supported version is `14` https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/package.json#L17 and so `??` supported
