### ISSUE TITLE
Make cssnano an optional dependecy

### ISSUE THREAD

**Issue by ankurk91** [webpack-contrib/css-minimizer-webpack-plugin#207]
### Modification Proposal
[cssnano](https://packagephobia.com/result?p=cssnano) takes around 7.5 MB on disk, people who opt-in to use `esbuild` OR `lightningcss` are forced to install cssnano as well.

* [ ] Move `cssnano` to peer dependency
* [ ] Update project read-me to install the default minifier (cssnano) along with this `css-minimizer-webpack-plugin`

**Comment by alexander-akait** [comment]
We want to provide the working plugin out of box, cssnano is stable, so I prefer to keep it in deps by default, in future we will revisit it, but not now

**Comment by ankurk91** [comment]
Okay thanks
