### ISSUE TITLE
Support for experimental animation-timeline CSS property

### ISSUE THREAD

**Issue by kevinfarrugia** [webpack-contrib/css-minimizer-webpack-plugin#240]
### Bug report

Experimental [`animation-timeline`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline) CSS property is not supported.

### Actual Behavior

The `animation-timeline` is added as a CSS property beneath `animation`.  `css-minimizer-webpack-plugin` will change the order of the output CSS causing the `animation-timeline` to be overridden by the `animation` shorthand property.

**Input**
```css
.progress-bar {
  animation: grow linear forwards;
  animation-timeline: scroll(block root);
}
```

**Output**
```css
.progress-bar{animation-timeline:scroll(block root);animation:grow linear forwards;}
```

### Expected Behavior

It should preserve the order of these two properties in respect of each other. So `animation-timeline` should always be before `animation` if it is declared in that order in the source.

### How Do We Reproduce?

Repro: https://github.com/kevinfarrugia/mini-css-extract-plugin-repro/tree/animation-timeline

1. Download the [repository](https://github.com/kevinfarrugia/mini-css-extract-plugin-repro/tree/animation-timeline)
2. Checkout the branch: `git checkout animation-timeline`
3. Install dependencies: `npm install`
4. Run in development mode (does not run `css-minimizer-webpack-plugin`) and notice the red progress bar scroll animation: `npm run dev`
5. Run in production mode (includes `css-minimizer-webpack-plugin` optimization) and notice the red progress bar is no longer animated: `npm start`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.64 GB / 15.26 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
  Packages:
    css-loader: ^6.8.1 => 6.8.1 
    css-minimizer-webpack-plugin: ^5.0.1 => 5.0.1 
    webpack: ^5.88.2 => 5.88.2 
    webpack-cli: ^5.1.4 => 5.1.4 
    webpack-dev-server: ^4.15.1 => 4.15.1 
```

**Comment by kevinfarrugia** [comment]
On further reading, the issue originates from [cssnano](https://github.com/cssnano/cssnano/issues/1514).

**Comment by kevinfarrugia** [comment]
Workaround:

```js
		new CssMinimizerPlugin({
		  minimizerOptions: {
		    preset: ["default", { cssDeclarationSorter: false }],
		  },
		}),
```

**Comment by Siilwyn** [comment]
Upstream fix: https://github.com/cssnano/cssnano/pull/1521/
