### ISSUE TITLE
Wrong declaration of runtime dependencies 

### ISSUE THREAD

**Issue by GiladShoham** [webpack-contrib/css-minimizer-webpack-plugin#244]
### Actual Behavior

Getting unresolved module errors
```
✘ [ERROR] Could not resolve "@parcel/css"
    <path>/node_modules/css-minimizer-webpack-plugin/dist/utils.js:300:28:
      300 │   const parcelCss = require("@parcel/css");
          ╵                             ~~~~~~~~~~~~~
  You can mark the path "@parcel/css" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
✘ [ERROR] Could not resolve "lightningcss"
    <path>/node_modules/css-minimizer-webpack-plugin/dist/utils.js:342:31:
      342 │   const lightningCss = require("lightningcss");
          ╵                                ~~~~~~~~~~~~~~
  You can mark the path "lightningcss" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
✘ [ERROR] Could not resolve "@swc/css"
    <path>/node_modules/css-minimizer-webpack-plugin/dist/utils.js:381:22:
      381 │   const swc = require("@swc/css");
          ╵                       ~~~~~~~~~~
```
Used config for the plugin:
```
new CssMinimizerPlugin({
            minimizerOptions: {
              preset: [
                'default',
                {
                  minifyFontValues: { removeQuotes: false },
                },
              ],
            },
          }),
```

This is a result of having these dependencies configured as devDependencies instead of as runtime dependencies, but used in runtime.

### Expected Behavior

The relevant dependencies should be moved to the `dependencies` section from the `devDependencies` to ensure they are available at runtime. 

### How Do We Reproduce?

This should be able to be reproducible by just applying the config attached above for the plugin.

**Comment by alexander-akait** [comment]
@GiladShoham I think you do something wrong because `require("@parcel/css")` is lazy loaded and it is in optional peerDeps, feel free to provide reproducible test repo and I will show how to fix it

@krutoo Please use `new CSSMinimizerWebpackPlugin<CustomOptions>({})` or `new CSSMinimizerWebpackPlugin<import("lightningcss").Options>()` (the last is pseudo code you need to check types inside `lightningcss`)

**Comment by zkochan** [comment]
I see that `@parcel/css` is an optional peer dependency. However, if the package doesn't work without `@parcel/css`, which seems to be the case, then I guess it should be a regular peer dependency.

**Comment by alexander-akait** [comment]
Please use `lightningcss`, instead `@parcel/css`, but both works correctly

**Comment by GiladShoham** [comment]
I think that what @zkochan is saying is that if you get into @parcel/css by default in runtime, it shouldn't be an optional.
