### ISSUE TITLE
Can we ignore some code while minify css file?

### ISSUE THREAD

**Issue by shamim-apex** [webpack-contrib/css-minimizer-webpack-plugin#258]
For example i wan't to put some logic in my css class like

.background {
<# if(variable == true) {>
background: transparent;
<# }
}

and the plug in let me ignore these <# #> syntax and build it successfully.
Documentation Is:

[x ] Missing
[x ] Needed
[ x] Confusing
[ x] Not Sure?

**Comment by alexander-akait** [comment]
Sorry, it is impossible, but some minimizers allows to insert custom comments to ignore some sections, but default we use cssnano and it is impossible, anyway you can insert some code after minimizer
