### ISSUE TITLE
Column gap gets overridden by gap

### ISSUE THREAD

**Issue by MateuszGroth** [webpack-contrib/css-minimizer-webpack-plugin#259]
### Bug report

Sorting the CSS attributes causes the wrong styles to take precedence

### Actual Behavior

Class written like that
```
.card {
   gap: 0;
   column-gap: 10px;
   row-gap: 15px;
}
```

is processed to the following output
```
.card {
  column-gap: 10px;
  gap: 0px;
  row-gap: 15px;
}
```

Causing column-gap to be overridden by gap

### Expected Behavior

```
.card {
  gap: 10px 15px;
}
```

### How Do We Reproduce?

> npx webpack-cli info

```
  System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 75.31 MB / 16.00 GB
  Binaries:
    Node: 20.10.0 - /opt/homebrew/opt/nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/opt/nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 17.3.1
  Packages:
    css-loader: 6.10.0 => 6.10.0 
    css-minimizer-webpack-plugin: 6.0.0 => 6.0.0 
    eslint-webpack-plugin: 4.1.0 => 4.1.0 
    fork-ts-checker-webpack-plugin: 9.0.2 => 9.0.2 
    loader-utils: 3.2.1 => 3.2.1 
    sass-loader: 14.1.1 => 14.1.1 
    stylelint-webpack-plugin: 5.0.0 => 5.0.0 
    swc-loader: 0.2.6 => 0.2.6 
    terser-webpack-plugin: 5.3.10 => 5.3.10 
    thread-loader: 4.0.2 => 4.0.2 
    tsconfig-paths-webpack-plugin: 4.1.0 => 4.1.0 
    webpack: 5.90.3 => 5.90.3 
    webpack-bundle-analyzer: 4.10.1 => 4.10.1 
    webpack-cli: 5.1.4 => 5.1.4 
    webpack-dev-server: 5.0.4 => 5.0.4 
    webpack-merge: 5.10.0 => 5.10.0 
```

**Comment by alexander-akait** [comment]
Close in favor https://github.com/cssnano/cssnano/issues/1588

**Comment by ludofischer** [comment]
Is this a bug in `css-declaration-sorter`, because `column-gap` is missing from https://github.com/Siilwyn/css-declaration-sorter/blob/master/src/core/shorthand-data.mjs

**Comment by MateuszGroth** [comment]
Looks like it was taken care of https://github.com/Siilwyn/css-declaration-sorter/issues/380

Waiting for patches :D

**Comment by ludofischer** [comment]
The fix has already been released in cssnano 6.1.2

**Comment by MateuszGroth** [comment]
Right, however, the lock files on css-minimizer should point to a higher version of cssnano to truly fix the issue

**Comment by alexander-akait** [comment]
@MateuszGroth you can update your deps locally, there is no sense to make a release on very fix in dependecies

**Comment by MateuszGroth** [comment]
I know I can. Still, I see it a little bit differently. It is worth a release to me. Apparently it is also worth it for cssnano, as they patched it with a release

**Comment by MateuszGroth** [comment]
Without a patch, every project that uses it and is not aware of such bug will keep having it in case they are not updating their locks. Not insisting tho. Just thinking out loud
