### ISSUE TITLE
Misleading webpack configuration

### ISSUE THREAD

**Issue by herrvigg** [webpack-contrib/css-minimizer-webpack-plugin#30]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I don't think it's a good suggestion to define the webpack configuration as such:
```
  optimization: {
    minimize: true,
    minimizer: [new CssMinimizerPlugin()],
  },
```
Problem: the default JS minimizer (Terser) will **not** be invoked anymore and i don't know how to invoke it without installing it explicitly... It goes against common sense to disable a much wanted behavior especially since this plugin is also about minimization.

### Your Proposal for Changes

It seems enough to instantiate an object like this:
```
    plugins: [
        new CssMinimizerPlugin()
    ]
 ```
Like this you don't need to touch the list of minimizers in the optimization entry and you can still have any other plugin in this list.

**Comment by evilebottnawi** [comment]
Yes, we need to improve it, anyway you should put it in `minimizer`, webpack@5 supports syntax:
```
optimization: {
    minimize: true,
    minimizer: ['...', new CssMinimizerPlugin()],
  },
```

**Comment by herrvigg** [comment]
Interesting! I didn't know this was possible. Yes that looks better. I understand you want to keep the optimization entry for all the other options.

**Comment by evilebottnawi** [comment]
@herrvigg Yes, I think we backport this feature for webpack@4, WIP on this

**Comment by herrvigg** [comment]
Sounds good! Feel free to close the ticket.

**Comment by evilebottnawi** [comment]
@herrvigg I think we will close it after updating docs

**Comment by evilebottnawi** [comment]
ETA for webpack@5 is `2020-10-10`, so we decide do not backport this feature, there are a lot of work for us, sorry :disappointed:

**Comment by herrvigg** [comment]
No worries, still it would be nice to get in future releases.

**Comment by herrvigg** [comment]
Also thank you for the information and the good work! Keep it on! :)
