### ISSUE TITLE
Set appropriate defaults for clean-css and csso

### ISSUE THREAD

**Issue by rightaway** [webpack-contrib/css-minimizer-webpack-plugin#50]
### Feature Proposal

Allow clean-css and csso to be set as configuration options, and appropriate defaults applied. It's quite convenient to use default of cssnano, where you just need to set the cssnano options. But if you want to use any of the alternatives, you need a lot of configuration to override the minify function as shown in readme. It could just be given as a config value or which minifier you want to use, and appropriate defaults set.

**Comment by alexander-akait** [comment]
clean-css and csso have own default good options, what you need?

**Comment by rightaway** [comment]
I mean not having to provide a custom `minify` function to use those alternatives, like we don't need to provide it for cssnano.

**Comment by alexander-akait** [comment]
> I mean not having to provide a custom minify function to use those alternatives

Sorry, no, we can't do it, because you can have all minimizers in node_modules and we don't who do you want to run

**Comment by rightaway** [comment]
Would be impossible to support any minimizer, but maybe just for the big 3 alternatives that everyone uses (cssnano, clean-css, csso) could be good to leave it as a configuration parameter of which one you want to choose, with cssnano being the default.

**Comment by alexander-akait** [comment]
But they already have good default options, I don't understand what you want from this plugin

**Comment by rightaway** [comment]
Something like this which would be enough to configure it to use clean-css instead of cssnano. And the minimizerOptions are specific for clean-css. This would make it simple for people to try out all 3 alternatives to see which results in best result.

```
new CssMinimizerPlugin({
    type: "clean-css",
    minimizerOptions: optionsForCleanCss
})
```

**Comment by alexander-akait** [comment]
Again - `clean-css` and other minimizers have own default options, we can't set something by default because it can be unsafe in some cases, so only you should set options, cssnano has safe transformations and they applied by default

**Comment by rightaway** [comment]
If using something like cssnano that has safe transformations then you can enable the `default` preset out of the box, as is being done, but if using one of the others then no defaults would be applied and you'd have to add all transformations to `minimizerOptions`.

The main idea of this feature request is the addition of `type` property that allows you to specify a different minimizer without having to provide an entire `minify` function, when all you really need to do is pass some options to it for how you'd like it to do the minimization.

**Comment by alexander-akait** [comment]
Different versions of minimizers have different Node.js API

**Comment by alexander-akait** [comment]
What is the problem setup function? We even describe it in docs, just copy paste

**Comment by rightaway** [comment]
Not a problem just a matter of ease of use. The simpler it is the more likely people to try all minimizers and see which works for best with their code instead of sticking with the default.

**Comment by alexander-akait** [comment]
You can try minimizers without webpack, it is even better
