### ISSUE TITLE
Allow providing custom PostCSS options

### ISSUE THREAD

**Issue by IlCallo** [webpack-contrib/css-minimizer-webpack-plugin#54]
- Operating System: Ubuntu 18.04
- Node Version: 12.14.0
- NPM Version: 6.13.4
- webpack Version: 4
- css-minimizer-webpack-plugin Version: 1.2.0

### Feature Proposal
Allow specifying custom options for PostCSS process, as https://github.com/NMFR/optimize-css-assets-webpack-plugin does (`cssProcessorOptions` option).
The options object is defined [here](https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/53cba6923afdb13284e5a6485e04309ee94b93a5/src/minify.js#L21) and cannot be extended.

### Feature Use Case
Into Quasar Framework we use https://github.com/postcss/postcss-safe-parser via the `parser` PostCSS option.

A possible patch would be to copy/paste the internal minify function into an external provided `minify` one, with the options we prefer

**Comment by mutoe** [comment]
Are there any updates? If I want to use postcss-safe-parser now, is there any alternative?
