### ISSUE TITLE
Update to cssnano@^5.0.0

### ISSUE THREAD

**Issue by lopopolo** [webpack-contrib/css-minimizer-webpack-plugin#60]
I don't see an issue for this, so thought I'd file this to track it.

### Feature Proposal

Update to cssnano@^5.0.0 once it is released. https://github.com/cssnano/cssnano/pull/975, https://github.com/cssnano/cssnano/pull/998.

### Feature Use Case

Deduplicate postcss dependencies in `node_modules` when using `css-minimizer-webpack-plugin` and `css-loader`.

**Comment by alexander-akait** [comment]
cssnano v5 is only in rc

**Comment by alexander-akait** [comment]
Fixed in master, release will be in near future (I think today)
