### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated

### ISSUE THREAD

**Issue by markcampbell24** [webpack-contrib/css-minimizer-webpack-plugin#61]
- Operating System: Windows 10
- Node Version: 14.15.5
- NPM Version: 6.14.11
- webpack Version: 5.24.2
- css-minimizer-webpack-plugin Version: 1.2.0

### Expected Behavior

Webpack build should produce no deprecation warnings relating to css-minimizer-webpack-plugin

### Actual Behavior

Following deprecation notice logged in console:

(node:21104) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option) 

This is traceable back to the css-minimizer-webpack-plugin by running:

> node --trace-deprecation node_modules/webpack/bin/webpack.js

### Code

Relevant snippets from webpack.config.js
```
optimization: {
    minimize: true,
    minimizer: [new OptimizeCSSAssetsPlugin({}), new TerserPlugin()],
    splitChunks: {
      chunks: 'all',
    }
  },
```

### How Do We Reproduce?

I see the warning message whenever running webpack build with the plugin enabled

**Comment by alexander-akait** [comment]
It means you still webpack v4 in deps, run `npm ls webpack` (here check https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/src/index.js#L445)

**Comment by markcampbell24** [comment]
@alexander-akait Ah, I see now, gotcha! Thanks Alexander thats fixed it for me
