### ISSUE TITLE
Not working with 2 minimizers

### ISSUE THREAD

**Issue by RDIL** [webpack-contrib/css-minimizer-webpack-plugin#62]
- Operating System: n/a
- Node Version: 12 and 14 both
- NPM Version: latest 6.x
- webpack Version: 5.24.2
- css-minimizer-webpack-plugin Version: 1.2.0

### Expected Behavior

In https://github.com/facebook/docusaurus/pull/4089, we use 2 minimizers.  It appears that one of them isn't getting applied because the css has unexpectedly raised in size by 4kb.  Any support or thoughts would be appreciated.

### Actual Behavior

It doesn't appear to be performing the same optimization

### Code

See the code below this discussion https://github.com/facebook/docusaurus/pull/4089/files#r588305123

### How Do We Reproduce?

https://github.com/facebook/docusaurus/pull/4089
It worked with css-optimizer-webpack-plugin, now it doesn't

**Comment by alexander-akait** [comment]
@RDIL Can you provide link on configuration, I want to assign a task to another person from the team, thanks

**Comment by RDIL** [comment]
The config is located here in this file: https://github.com/facebook/docusaurus/blob/d726233b5c197a25f65b0ba842113fba7be4f1a6/packages/docusaurus/src/webpack/utils.ts

**Comment by lex111** [comment]
It might be useful the initial working  version with using two `CssMinimizerPlugin` instances. The link above contains its "improved" version (with one instance), which didn't work for us anyway.

https://github.com/facebook/docusaurus/blob/e46832c914a6ed6ac4711528154f2b2459ad4305/packages/docusaurus/src/webpack/utils.ts#L456-L492

**Comment by alexander-akait** [comment]
@lex111 yep, here interesting case, we adding the `minized` flag to asset info to avoid double minification, because you can use `childCompilers` so assets already minimized, this case is not working due this, I think your solution is good, in theory we can add extra info to check it is other minimizer plugin, so it will workout of box, I will look at near future how we can solve it better

**Comment by lex111** [comment]
@alexander-akait it would be great, we are really looking forward to it. I even thought this case could be handled by allowing to specify both fields `preset` and `minify` at the same time. This way, the `preset` is called first, and after it the code from `minify` field is executed as extra minification. (Or something similar within one instance `CssMinimizerPlugin`).
