### ISSUE TITLE
Add support for `preamble` option

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/css-minimizer-webpack-plugin#64]
Hi webpack team :wave:

I am currently upgrading a project setup to `webpack@5` and want to move from `optimize-css-assets-webpack-plugin@5.0.4` to `css-minimizer-webpack-plugin@1.0.2`, but it looks like there is not way to add a simple banner at the top of the emitted CSS asset, so I am unable to put a preamble the same way I was doing this on `webpack@4`:

```js
optimization: {
  minimizer: [
    new TerserPlugin({
      extractComments: false,
      terserOptions: {
        output: {
          comments: false,
          preamble: preamble, // <-- add preamble to the app.js asset
        },
      },
    }),
  ],
},
plugins: [
  new OptimizeCSSAssetsPlugin({
    cssProcessorPluginOptions: {
      preset: ['default', {
        discardComments: {
          removeAll: true,
        },
      }],
    },
  }),
  new webpack.BannerPlugin({
    raw: true,
    banner: () => {
      return preamble; // <-- add preamble to the app.css asset
    },
  }),
  // ...
]
```

I guess it's because `new CssMinimizerPlugin` move into `webpack.optimization.minimizer` array :thinking: 
I think it's not a bug, more a feature that is not supported yet.

### Feature Proposal

It would be good to have an option to add a banner/preamble at the top of the emitted asset when `css-minimizer-webpack-plugin` minimization process ends.

### Feature Use Case

Same as `TerserPlugin` with the `preamble` option: easy to implement and use without any additional plugins.

> May be the option should go into CSSNano.. not sure about that.

**Comment by alexander-akait** [comment]
Here interesting problem - `BannerPlugin` added comment(s), but `cssnano` remove them due `removeAll: true`, I think we need here an option for banner plugin... like `event: 'before-minimizer'` and `event: 'after-minimizer'`

**Comment by xavierfoucrier** [comment]
Hi @alexander-akait,

Thanks for taking time to answer.
You are right, removing `removeAll: true` on `cssnano` do the job, but all other comments inside source stay in the final bundle

Fixing on `BannerPlugin` sounds good :wink:

**Comment by xavierfoucrier** [comment]
Hi @alexander-akait,

Just to know on my side, could this be fixed in the next few weeks?
Thanks a lot!

> I know you have a lot of work in all webpack repos, so don't worry, it's just to know on my side and plan the upgrade.

**Comment by alexander-akait** [comment]
Yep, let's give me time to think about it, should not be hard

**Comment by xavierfoucrier** [comment]
Thanks a lot @alexander-akait!

**Comment by xavierfoucrier** [comment]
Hello @alexander-akait,

Any update on this? :roll_eyes: :kissing_heart: 

> I have tried to downgrade to investigate further and noticed that this happened anyway when moving from `optimize-css-assets-webpack-plugin@5.0.0` to `optimize-css-assets-webpack-plugin@5.0.1` - `cssnano` moves from `4.0.2` to `4.1.0` - , but of course this version in only compatible with `webpack@4`.

**Comment by alexander-akait** [comment]
Hi, sorry no, still in my todo, I can provide place where we can implement this and you will help me

**Comment by xavierfoucrier** [comment]
@alexander-akait sure I can help course, I think you are better for webpack core code structure, but I can test and give feedback :wink:

**Comment by xavierfoucrier** [comment]
Hello @alexander-akait, please let me know when you have time to build something, this way I can test and help :wink:

**Comment by xavierfoucrier** [comment]
@alexander-akait, I have finally decided to drop banner / top comments from my css / js assets.

> Feel free to close this issue, or let it open to fix later.

**Comment by vankop** [comment]
maybe for raw option we should use another stage? 🤔

**Comment by alexander-akait** [comment]
Because `raw` can used for any stage
