### ISSUE TITLE
Example webpack configuration is misleading

### ISSUE THREAD

**Issue by sportshead** [webpack-contrib/css-minimizer-webpack-plugin#65]
Documentation Is: very misleading

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Extremely misleading

### Please Explain in Detail...
If `mini-css-extract-plugin` is not required for this plugin to function, it should not be included in the example webpack configuration. Why? I was following this example configuration, and saw that I needed to `require` two packages: `mini-css-extract-plugin` and `css-minimizer-webpack-plugin`. I thought to myself, "ok, this is weird, shouldn't the css-minimizer-webpack-plugin already call mini-css-extract-plugin if its a dependency?" But, after attempting to build unsuccessfully, I found out that `mini-css-extract-plugin` is not a peerDependency, dependency, or devDependency of css-minimizer-webpack-plugin, ***meaning that I have to manually install it myself.*** At this point I was getting quite confused, and installed mini-css-extract-plugin, thinking it would further improve my file size. But lo and behold, the example configuration **does not even function!** Adding the `MiniCssExtractPlugin.loader` loader to my CSS section does nothing but make the plugin complain that I did not set it up properly. So I added mini-css-extract-plugin to my plugins list, and what does that do? Nothing but more errors regarding the abscense of `document`. I then uninstalled mini-css-extract-plugin to find that not using it at all does not affect the performance of css-minimizer-webpack-plugin. If mini-css-extract-plugin serves no purpose regarding this plugin, it should not have been mentioned at all in the example webpack configuration.

### Your Proposal for Changes
If mini-css-extract-plugin is not required for this plugin to work, it should not be mentioned in the example configuration. A suggestion to use this plugin may be good, but it should not be in the example configuration.

**Comment by alexander-akait** [comment]
> If mini-css-extract-plugin is not required for this plugin to function, it should not be included in the example webpack configuration.

`mini-css-extract-plugin` is not required to working with this plugin, you can use `copy-webpack-plugin` and copy CSS assets, other loaders and plugins can emit CSS files too. `mini-css-extract-plugin` required to compile and extract CSS from from `import './style.css';`. Most of developers use `mini-css-extract-plugin` so we added it to docs. Feel free to feedback

**Comment by sportshead** [comment]
> 
> 
> > If mini-css-extract-plugin is not required for this plugin to function, it should not be included in the example webpack configuration.
> 
> `mini-css-extract-plugin` is not required to working with this plugin, you can use `copy-webpack-plugin` and copy CSS assets, other loaders and plugins can emit CSS files too. `mini-css-extract-plugin` required to compile and extract CSS from from `import './style.css';`. Most of developers use `mini-css-extract-plugin` so we added it to docs. Feel free to feedback

My feedback is that this should be removed. I feel that this comment is redundant, as your quoted phrase indicates "it should not be included in the example webpack configuration" which is my feedback to you.

**Comment by alexander-akait** [comment]
What it the problem?

**Comment by sportshead** [comment]
> 
> 
> What it the problem?

The problem, as I have stated multiple times before, is that the example webpack configuration is misleading. Everything that mentions mini-css-extract-plugin should be **removed**, and be replaced with a _suggestion_ instead.

**Comment by hyoretsu** [comment]
To be fair, they never mentioned it's required and if you're looking this far in, I suppose you should already know what alternatives there are to MiniCssExtract.
