### ISSUE TITLE
minimizerOptions fails when not serializable (using import/require)

### ISSUE THREAD

**Issue by slorber** [webpack-contrib/css-minimizer-webpack-plugin#83]
- Operating System: macos
- Node Version: 14.16
- NPM Version: 6
- webpack Version: 5.28.0
- css-minimizer-webpack-plugin Version: 2.0.0

### Expected Behavior

Using cssnano preset with a require call instead of a string preset + options object:

```js
      new CssMinimizerPlugin({
        minimizerOptions: [
          // CssNano options
          {
            preset: require('cssnano-preset-advanced'), 
          },
        ],
        minify: [
          CssMinimizerPlugin.cssnanoMinify,
        ],
      })
```

### Actual Behavior

> ReferenceError: defaultOpts is not defined

![image](https://user-images.githubusercontent.com/749374/115155684-4c85e200-a081-11eb-9145-cbc8b419f38a.png)

Also tried with `preset: require('cssnano-preset-advanced')(opts)` (looks like the correct way to me) and got another similar error:

![image](https://user-images.githubusercontent.com/749374/115155830-e51c6200-a081-11eb-94ad-de6e50f8aad8.png)

> ReferenceError: _commentRemover is not defined

### Code

cf above

### How Do We Reproduce?

cf above

-------

For context, Docusaurus is migrating to Webpack 5 (@alexander-akait helped review a bit our PR https://github.com/facebook/docusaurus/pull/4089)

We have a custom CSSNano preset with some custom config + an additional postcss plugin: https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-cssnano-preset

It's not 100% clear to me how I am supposed to provide our custom Cssnano preset to the CssMinimizer, as it seems there's some evaluation of options that prevent imports/requires in our preset. Do you have an example to share?

I believe that it is a similar issue that @RDIL already reported here: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/58

**Comment by slorber** [comment]
Actually, this seems to work:

```js
{
  preset: require.resolve('@docusaurus/cssnano-preset'),
}
```

Still think that what I tried should work.
But maybe just documenting this better or throwing a user-friendly error could be good enough?

**Comment by alexander-akait** [comment]
> But maybe just documenting this better or throwing a user-friendly error could be good enough?

Yep, here problems with multi threading, we need serialize options and require is broken in this case, so we should use `string` here (i.e. `require.resolve`)

**Comment by alexander-akait** [comment]
@slorber Can you look at https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/84/?
