### ISSUE TITLE
Minified file contains 2 links to source map

### ISSUE THREAD

**Issue by hyoretsu** [webpack-contrib/css-minimizer-webpack-plugin#85]
- Operating System: Ubuntu 20.10 (WSL in Windows 10)
- Node Version: 14.16.0
- NPM Version: 6.2.5 **(Using PNPM, not NPM)**
- webpack Version: 5.36.2
- css-minimizer-webpack-plugin Version: 2.0.0

### Expected Behavior

There should be a line with a link to source map location at the end of the file.

### Actual Behavior

There are 2 of said line, for some reason. The only difference between them is a space before the ending `*/`

### Code
https://gist.github.com/hyoretsu/d159f10cbee83a47d92a9789ac8bc4ef

### How Do We Reproduce?

Just import any CSS with the linked config and there should be 2 links in minified file.

**Comment by alexander-akait** [comment]
Why do you change `processorOptions`? postcss put this url in this case, we can't change postcss behavior

**Comment by hyoretsu** [comment]
Because if I don't, no souce map's created. Since I also can't simply pass a `{ sourceMap: true }` like in docs, because it throws this error (even though it's there when I use IntelliSense)
```
[webpack-cli] Failed to load '/home/hyoretsu/@Projects/reactjs-template/webpack.config.prod.ts' config
[webpack-cli] Invalid options object. Css Minimizer Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, minimizerOptions?, parallel?, warningsFilter?, minify? }
```

**Comment by alexander-akait** [comment]
You don't need the `sourceMap` option here, just set `devtool` and you will get source maps, in future `sourceMap` option will be removed from `css-loader`/`mini-css-extract-plugin` in favor `devtool: { stylesheet: true }`, default value is `devtool` (https://github.com/webpack-contrib/css-loader#sourcemap) for `css-loader` and other loaders too

**Comment by hyoretsu** [comment]
I'm now with no `sourceMap` in CssMinimizerPlugin, css-loader nor MiniCssExtractPlugin (which doesn't even accept one) and I do have `devtool: 'source-map'` in webpack. But still, I have no `.map` generated for CSS files, only JS.

**Comment by alexander-akait** [comment]
@hyoretsu `404` I don't have ability to look at private repos, you can look at all possible variants to setup here https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/test/sourceMap-option.test.js, as you can see in snapshots all works fine

**Comment by hyoretsu** [comment]
> @hyoretsu `404` I don't have ability to look at private repos, you can look at all possible variants to setup here https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/test/sourceMap-option.test.js, as you can see in snapshots all works fine

I'd forgot I was working on a private one, it's public now. I just went through the tests, but even when I try to mimic its CSS-related config I don't get a source-map. (Adding CSS to entry, putting CSSMinimizer before css-loader)

**Comment by alexander-akait** [comment]
Some notes:
- You don't need `CleanWebpackPlugin` look at `output.clean`
- Don't set `terserOptions.sourceMap`, because it will be ignored

You have invalid order of `CSS` rules:
```
{
  test: /\.css$/,
  use: [
    { loader: 'css-loader', options: [Object] },
    {
      loader: '/home/evilebottnawi/IdeaProjects/reactjs-template/node_modules/.pnpm/mini-css-extract-plugin@1.6.0_webpack@5.36.2/node_modules/mini-css-extract-plugin/dist/loader.js',
      options: [Object]
    }
  ],
  sideEffects: true
}
```

mini-css-extract-plugin should be before `css-loader` (i.e. above)

**Comment by hyoretsu** [comment]
I tried doing that, since it's that way in the snapshots you sent, but I got this error
```
./node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/cjs.js!./node_modules/.pnpm/file-loader@6.2.0_webpack@5.36.2/node_modules/file-loader/dist/cjs.js??ruleSet[1].rules[5].use[0]!./src/styles/custom.css 39 bytes [built] [1 error]
    

  ERROR in ./src/styles/custom.css (./node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/cjs.js!./node_modules/.pnpm/file-loader@6.2.0_webpack@5.36.2/node_modules/file-loader/dist/cjs.js??ruleSet[1].rules[5].use[0]!./src/styles/custom.css)
  Module build failed (from ./node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/cjs.js):
  CssSyntaxError

  (1:1) /home/hyoretsu/@Projects/reactjs-template/src/styles/custom.css Unknown word

  > 1 | export default __webpack_public_path__ + "static/media/custom.4029592e.css";
      | ^

  Child mini-css-extract-plugin /home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/cjs.js!/home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/file-loader@6.2.0_webpack@5.36.2/node_modules/file-loader/dist/cjs.js??ruleSet[1].rules[5].use[0]!/home/hyoretsu/@Projects/reactjs-template/src/styles/custom.css compiled with 1 error

ERROR in ./src/styles/custom.css
Module build failed (from ./node_modules/.pnpm/mini-css-extract-plugin@1.6.0_webpack@5.36.2/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) /home/hyoretsu/@Projects/reactjs-template/src/styles/custom.css Unknown word

> 1 | export default __webpack_public_path__ + "static/media/custom.4029592e.css";
    | ^

    at processResult (/home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.6.0/node_modules/webpack/lib/NormalModule.js:676:19)
    at /home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/webpack@5.36.2_webpack-cli@4.6.0/node_modules/webpack/lib/NormalModule.js:778:5
    at /home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/hyoretsu/@Projects/reactjs-template/node_modules/.pnpm/css-loader@5.2.4_webpack@5.36.2/node_modules/css-loader/dist/index.js:154:5)
 @ ./src/App.tsx 5:0-29
 @ ./src/index.tsx 3:0-24 6:30-33
 ```
The entire problem was the file-loader I'd got from CRA webpack config. It's also the reason why my CSS were being placed in the wrong folder. (And only then did MiniCssExtract start complaining, trying to figure that out with webpack-merge)

**Comment by alexander-akait** [comment]
I see, you don't need `file-loader` with webpack v5 too :smile:
