### ISSUE TITLE
preset lite + options doesn't pass options

### ISSUE THREAD

**Issue by natew** [webpack-contrib/css-minimizer-webpack-plugin#87]
- Operating System: Big Sur
- Node Version: 15
- webpack Version: 5.37
- css-minimizer-webpack-plugin Version: 2.0

```tsx
             new CssMinimizerPlugin({
                // this doesnt discard duplicates....
                minimizerOptions: {
                  preset: [
                    'lite',
                    {
                      discardDuplicates: true,
                    },
                  ],
                },
              }),
```

Using this config I'm unable to get cssnano to discard duplicates, tried a few different variants. Perhaps this isn't possible? But readme suggests it should work work.

**Comment by alexander-akait** [comment]
We pass all options directly to cssnano, if it is not working, it means bug on cssnano

**Comment by alexander-akait** [comment]
Yep, bug in `cssnano`, `cssnano` allows only disable plugin in preset and don't allow to enable them

**Comment by alexander-akait** [comment]
Reported https://github.com/cssnano/cssnano/issues/1098, nothing to fix here, thanks for the issue

**Comment by natew** [comment]
thank you!
