### ISSUE TITLE
README confusing about how to enable for development as well

### ISSUE THREAD

**Issue by mbertheau** [webpack-contrib/css-minimizer-webpack-plugin#90]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In [README.md](README.md) it says:

> **webpack.config.js**
 
> ```js
> const MiniCssExtractPlugin = require('mini-css-extract-plugin');
> const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');
> 
> module.exports = {
>   module: {
>     loaders: [
>       {
>         test: /.s?css$/,
>         use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
>       },
>     ],
>   },
>   optimization: {
>     minimize: true,
>     minimizer: [
>       // For webpack@5 you can use the `...` syntax to extend existing minimizers (i.e. `terser-webpack-plugin`), uncomment the next line
>       // `...`,
>       new CssMinimizerPlugin(),
>     ],
>   },
> };
> ```

> This will enable CSS optimization only in production mode.

Ok, so this example is for CSS optimization only in production mode.

> If you want to run it also in development set the `optimization.minimize` option to `true`.

Ok, to run it in development mode as well, set `optimization.minimize` option to `true`.

Wait: It's already `true` in the example?

### Your Proposal for Changes

I'm confused, so I don't know :) Either the example should be modified such that it actually enables CSS optimization **only in production mode**, or the explanation about how to enable CSS optimization **also in development mode** needs to be changed.

**Comment by alexander-akait** [comment]
> Wait: It's already true in the example?

Yes

`minimize: true` enables `minimizer` plugins, it is `true` by default in `mode: production`, but `false` in `development`, but you can set `true` and it will enable minimizers, I don't see what we can improve, but if you know, feel free to send a PR, anyway thanks
