### ISSUE TITLE
Update `css-nano` package

### ISSUE THREAD

**Issue by b-ponomarenko** [webpack-contrib/css-minimizer-webpack-plugin#95]
Using `css-minimizer-webpack-plugin` with version 5.0.0 or above brings problem which described [here](https://github.com/Siilwyn/css-declaration-sorter/issues/157). In order to fix that behavior you should update `css-nano` package to 5.0.5 (which actually latest version) and check that current of `css-declaration-sorter` package is 6.0.3

This is the dependency tree
```
$ npm ls css-declaration-sorter
css-minimizer-webpack-plugin@3.0.1 /Users/user/Desktop/css-minimizer-webpack-plugin
└─┬ cssnano@5.0.2
  └─┬ cssnano-preset-default@5.0.1
    └── css-declaration-sorter@6.0.0
```

- Operating System: MacOS 11.2.2
- Node Version: 14.16.0
- NPM Version: 7.11.0
- webpack Version: 5.36.2
- css-minimizer-webpack-plugin Version: 3.0.1

### Expected Behavior

described [here](https://github.com/Siilwyn/css-declaration-sorter/issues/157)

### Actual Behavior

described [here](https://github.com/Siilwyn/css-declaration-sorter/issues/157)

### How Do We Reproduce?

described [here](https://github.com/Siilwyn/css-declaration-sorter/issues/157)

**Comment by alexander-akait** [comment]
You can do it locally using `npm update`, we use `^` https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/package.json#L51, please read how `semver` works https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies
