### ISSUE TITLE
Some CSS keys were merged

### ISSUE THREAD

**Issue by Edge00** [webpack-contrib/css-minimizer-webpack-plugin#97]
before -> after  
`padding-bottom` were merge however `width` were not

![image](https://user-images.githubusercontent.com/23715779/121199607-a77bce80-c8a5-11eb-8f1b-4ef81270a81f.png)

**Comment by alexander-akait** [comment]
Please remove it to `cssnano`, we can't fix it here, we just plugin and run cssnano inside

**Comment by Edge00** [comment]
@alexander-akait OK
